# -*- coding: utf-8 -*-
"""generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sbwdxLrbdo9bElreixidlxLqXvj9p83_
"""

import random


for i in range(100): 
 letterLOWER = "abcdefghijklmnopqrstuvwxyz"
 letterUPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
 numbers = "0123456789"
 symbols = "$#@^*()[]{}"

 combination = letterLOWER + letterUPPER + numbers + symbols
 length = 6
 password = "".join(random.sample(combination, length))
 print(password)

pip install qrcode

"""nomes

"""

import qrcode
  
  
img  = qrcode.make( "https://www.youtube.com/watch?v=kcGM-aASglUimage.pil.PilImage")
type(img)
img.save("some_file.png")