# -*- coding: utf-8 -*-
"""GPA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJncFQost_UtbCjjtVI-bJW76O2jiHNl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

materias = ["Geography", "English", "P.E", "Religion", "Arts", "History", "Media", "Maths", "Portuguese", "Science"  ]
gpa = [3.96, 3.96, 3.86, 3.86, 3.8, 3.8, 3.8, 3.7, 3.56, 3.4]

plt.bar(materias, gpa, color='green')

df = pd.read_csv("GPA.csv")

df

df2 = df.sort_values(by="grade", ascending = False).head(10)

x = df2['subject']
y = df2['grade']

plt.figure(figsize= (15,8))
plt.bar(x, y, color = "green")